In [1]:
import numpy as np

In [2]:
# Vectorization

# 1D array
arr = np.array([1,2,3,4,5])
print(arr**2)
print(arr + 10)
arr2 = np.array([1,2,3,4,5])
print(arr+arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 2  4  6  8 10]


In [3]:
# Broadcasting
print(arr+5)

arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr+arr2)
print(arr.shape)
print(arr2.shape)

# what throws an error... 
# arr = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
# arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
# print(arr+arr2)
# print(arr.shape)
# print(arr2.shape)

[ 6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
(5,)
(2, 5)


In [4]:
# Normalization
# NOTE:
# Always normalize using the same array's mean and std
# Axis-based normalization is used for feature scaling in ML

print("For 1D array")
arr = np.array([1,2,3,4,5])
arr2D = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr-mean)/std_dev
print(normalized_arr)
print()

print("For 2D array")
mean2D = np.mean(arr2D)
std_dev_2D = np.std(arr2D)
normalized_arr_2D = (arr2D-mean2D)/std_dev_2D
print(normalized_arr_2D)
print(np.mean(normalized_arr_2D))
print(np.std(normalized_arr_2D))

For 1D array
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

For 2D array
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
0.0
1.0


In [5]:
# Mathematical Functions

# Aggregate Functions

arr = np.array([1,2,3,4,5])
print(f"Sum: {np.sum(arr)}")
print(f"Product: {np.prod(arr)}")
print(f"Minimum: {np.min(arr)}")
print(f"Maximum: {np.max(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"std: {np.std(arr)}")
print(f"Var: {np.var(arr)}") # Variance
print(f"Median: {np.median(arr)}")
print(f"Argmin: {np.argmin(arr)}") # Minimum Value's Index
print(f"Argmax: {np.argmax(arr)}") # Maximum Value's Index

Sum: 15
Product: 120
Minimum: 1
Maximum: 5
Mean: 3.0
std: 1.4142135623730951
Var: 2.0
Median: 3.0
Argmin: 0
Argmax: 4


In [6]:
# Power Functions
print(f"Square: {np.square(arr)}")
print(f"sqrt: {np.sqrt(arr)}")

# NOTE:
# np.pow() may work in older NumPy versions
# In NumPy 1.26+, use np.power() or ** operator
print(f"power: {np.power(arr,4)}")

Square: [ 1  4  9 16 25]
sqrt: [1.         1.41421356 1.73205081 2.         2.23606798]
power: [  1  16  81 256 625]


In [7]:
# Log and Exponential

print(f"log: {np.log(arr)}")
print(f"log10: {np.log10(arr)}")
print(f"log2: {np.log2(arr)}")
print(f"exp: {np.exp(arr)}")

log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
log10: [0.         0.30103    0.47712125 0.60205999 0.69897   ]
log2: [0.         1.         1.5849625  2.         2.32192809]
exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [8]:
# Rounding functions
arr = np.array([  2.71828183,   7.3890561,   20.08553692,  54.59815003, 148.4131591] )
print(f"Round: {np.round(arr)}")
print(f"floor: {np.floor(arr)}")
print(f"Ceil: {np.ceil(arr)}")
print(f"trunc: {np.trunc(arr)}")

Round: [  3.   7.  20.  55. 148.]
floor: [  2.   7.  20.  54. 148.]
Ceil: [  3.   8.  21.  55. 149.]
trunc: [  2.   7.  20.  54. 148.]


In [9]:
# Extra Functions
print(f"Unique: {np.unique(arr)}")
print(f"Sort: {np.sort(arr)}")
print(f"abs: {np.abs(arr)}")

Unique: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sort: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
abs: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [10]:
import numpy as np
print(np.__version__)


1.26.4
