In [2]:
import numpy as np
import time

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
# Comparision between python_list and Numpy Arrays

# Time Comparision
size = 1_00_000

# Python List
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python list takes = {end-start} seconds")

# Numpy arrays

np_arr = np.array(py_list)
start = time.time()
# Vectorization
sq_array = np_arr ** 2
end = time.time()
print(f"Numpy Array takes = {end-start} seconds")

Python list takes = 0.01690983772277832 seconds
Numpy Array takes = 0.0017781257629394531 seconds


In [ ]:
# Memory Comparision

import sys

print(f"Python List size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"Numpy Array size = {sys.getsizeof(np_arr) * len(np_arr)} bytes")

Python List size = 80005600000 bytes
Numpy Array size = 40011200000 bytes


In [8]:
# create - from lists
# Numpy Arrays are homogeneous
print("arr:")
arr = np.array([1,2,3,4,5])
print(arr,type(arr)) 
# datatype 
print(f"Datatype of arr: {arr.dtype}") # dtype integers
# shape or dimention 
print(f"Shape of arr: {arr.shape}")
print()
# If one of the element is string then all other elements are considered as strings.
print("arr2:")
arr2 = np.array([1,2,3,4,"Alice Mary"])
print(arr2,type(arr2)) 
# datatype 
print(f"Datatype of arr2: {arr2.dtype}") # dtype unicode 
# shape or dimention 
print(f"Shape of arr2: {arr2.shape}")

arr:
[1 2 3 4 5] <class 'numpy.ndarray'>
Datatype of arr: int32
Shape of arr: (5,)

arr2
['1' '2' '3' '4' 'Alice Mary'] <class 'numpy.ndarray'>
Datatype of arr2: <U11
Shape of arr2: (5,)


In [16]:
# 2D array
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

# shape or dimention
print(f"Dimension of 2D array: {arr2D.shape}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of 2D array: (3, 3)


In [28]:
# Creating Numpy Arrays in different ways
print("Create arrays prefilled by Zeros")
arr_zeros = np.zeros((2,3),dtype="int64") # default dtype: float
print(arr_zeros)
print(f"Dimension of arr_zeros: {arr_zeros.shape}")
print() 

print("Create arrays prefilled by Ones")
arr_ones = np.ones((5,),dtype="int64") # prefill with one 
print(arr_ones)
print(f"Dimension of arr_ones: {arr_ones.shape}")
print()

print("Create arrays prefilled by Specific Value")
arr_val = np.full((2,3),100,dtype="int64") # prefill with value
print(arr_val)
print(f"Dimension of arr_val: {arr_val.shape}")
print()

print("Create arrays for Identity Matrix") # square matrix their diagonal values one either of them zero
arr_eye = np.eye(3,dtype = "int64")
print(arr_eye)
print(f"Dimension of arr_eye: {arr_eye.shape}")
print()

print("Create arrays using range function")
arr_range = np.arange(1,11)
print(arr_range)
print(f"Dimension of array create using range: {arr_range.shape}")
print()

print("Create arrays that are evenly spaced")
arr_spaced = np.linspace(1,100,3)
print(arr_spaced)
print()



Create arrays prefilled by Zeros
[[0 0 0]
 [0 0 0]]
Dimension of arr_zeros: (2, 3)

Create arrays prefilled by Ones
[1 1 1 1 1]
Dimension of arr_ones: (5,)

Create arrays prefilled by Specific Value
[[100 100 100]
 [100 100 100]]
Dimension of arr_val: (2, 3)

Create arrays for Identity Matrix
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Dimension of arr_eye: (3, 3)

Create arrays using range function
[ 1  2  3  4  5  6  7  8  9 10]
Dimension of array create using range: (10,)

Create arrays that are evenly spaced
[  1.   50.5 100. ]



In [38]:
# Properties 

np_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np_arr.shape) # dimensions = m*n
print(np_arr.size) # total elements = 9
print(np_arr.dtype) # Integers
print(np_arr.ndim) # number of dimensions
print()
# type casting
float_np = np_arr.astype(np.float64)
print(float_np)
print(f"Type: {float_np.dtype}")

(3, 3)
9
int32
2

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Type: float64


In [44]:
# Operations on Numpy Arrays

# Reshaping
print("Reshape an Array")
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print()
reshaped = arr.reshape((3,2))
print(reshaped)
print(reshaped.shape)
print()

# Flattenning
print("Flatten an Array(1D array)")
flattened = arr.flatten() 
print(flattened)

Reshape an Array
[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

Flatten an Array(1D array)
[1 2 3 4 5 6]


In [52]:
# Indexing

print("Indexing")
# 1D array
arr = np.array([1,2,3,4,5,6])
print(arr[0]) # 1
print(arr[3]) # 4
print()
# 2D array
arr_2D = np.array([[1,2,3],[4,5,6]])
print(arr_2D[0][0]) # 1
print()

# Fancy Indexing
print("Fancy Indexing")
arr = np.array([1,2,3,4,5,6])
idx = [0,1,2]
print(arr[idx])
print()

# Boolean Indexing
print("Boolean Indexing")
arr = np.array([1,2,3,4,5,6])
print(arr[arr > 3]) #  greater than 3
print(arr[arr % 2 == 0]) # printing even values
print(arr[arr % 2 != 0]) # printing odd values
print()


Indexing
1
4

1

Fancy Indexing
[1 2 3]

Boolean Indexing
[4 5 6]
[2 4 6]
[1 3 5]



In [65]:
# Slicing - similar to list

print("Slicing In Numpy")
arr = np.array([1,2,3,4,5,6])
print(arr[1:5])
print()
# In numpy slicing, it doesnt copy any elements it just help us to view.
# To view specific indexed values by not occupying any extra memory space.

# python slicing Vs Numpy Slicing
print("python slicing Vs Numpy Slicing")
print("Python Slicing")
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200 # changes doesnt affect the original array.
print(sub_list)
print(nums)
print()

print("Numpy arrays Slicing")
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0] = 200 # changes affect the original array aswell
print(sub_arr)
print(arr)
print()

print("Without affecting")
# To slice without affecting we need to use copy()
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3].copy()
print(sub_arr)
sub_arr[0] = 200 # changes affect the original array aswell
print(sub_arr)
print(arr)

Slicing In Numpy
[2 3 4 5]

python slicing Vs Numpy Slicing
Python Slicing
[2, 3]
[200, 3]
[1, 2, 3, 4, 5]

Numpy arrays Slicing
[2 3]
[200   3]
[  1 200   3   4   5]

Without affecting
[2 3]
[200   3]
[1 2 3 4 5]


In [68]:
# objects in numpy

arr = np.array(["Daisy",{1,2,3},3.0])
print(arr,arr.dtype)

# Numpy arrays can be heterogeneous, but more than one data type found in array.
# It is considered as an object in Numpy 

['Daisy' {1, 2, 3} 3.0] object


In [77]:
# Multidimensional Arrays - Axes

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

# Sum of columns 
print(np.sum(arr2D))
sum_of_col = np.sum(arr2D,axis=0)
print(sum_of_col)

# Sum of rows
sum_of_rows = np.sum(arr2D,axis=1)
print(sum_of_rows)

# Slicing in 2D
print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [85]:
# 3D Arrays
print("3D arrays in Numpy")
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D)
print(f"Shape: {arr3D.shape}")

print("Indexing in 3D arrays")
# Indexing
print(arr3D[0,1,1])

print("Slicing in 3D arrays")
# Slicing
print(arr3D[:,0,:]) # first row from both the layers
print(arr3D[:,:,0])

print("Manipulate arrays elements with slicing")
# Manipulate array elements with slicing
arr3D [:,:,0] = 100
print(arr3D)

3D arrays in Numpy
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Shape: (2, 3, 2)
Indexing in 3D arrays
4
Slicing in 3D arrays
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
Manipulate arrays elements with slicing
[[[100   2]
  [100   4]
  [100   6]]

 [[100   8]
  [100  10]
  [100  12]]]
